language: node_js
node_js:
  - 'lts/*'
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master
